# Generated by Django 3.2 on 2021-05-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='StockBasic',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='股票/标的代码')),
                ('name', models.CharField(default='', max_length=64, verbose_name='名称')),
                ('area', models.CharField(default='', max_length=32, verbose_name='地域')),
                ('market', models.CharField(default='', max_length=16, verbose_name='市场类型')),
                ('exchange', models.CharField(max_length=16, verbose_name='交易所代码')),
                ('industry', models.CharField(default='', max_length=16, verbose_name='所属行业')),
                ('curr_type', models.CharField(max_length=16, verbose_name='交易货币')),
                ('list_status', models.CharField(max_length=16, verbose_name='上市状态')),
                ('list_date', models.DateTimeField(max_length=16, verbose_name='上市时期')),
                ('delist_date', models.DateTimeField(max_length=16, verbose_name='退市日期')),
                ('is_hs', models.CharField(default='', max_length=16, verbose_name='沪深港通')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quant.question')),
            ],
        ),
    ]
