# Generated by Django 3.2 on 2021-05-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
