# Generated by Django 3.2.7 on 2021-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0002_auto_20210502_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='kline_1d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, max_length=16, verbose_name='交易时间')),
                ('code', models.CharField(db_index=True, default='', max_length=64, verbose_name='名称')),
                ('open', models.DecimalField(decimal_places='4', default='', max_digits='10', verbose_name='开盘价格')),
                ('close', models.DecimalField(decimal_places='4', default='', max_digits='10', verbose_name='收盘价格')),
                ('high', models.DecimalField(decimal_places='4', default='', max_digits='10', verbose_name='最高价格')),
                ('low', models.DecimalField(decimal_places='4', default='', max_digits='10', verbose_name='最低价格')),
                ('preclose', models.DecimalField(decimal_places='4', default='', max_digits='10', verbose_name='前一天收盘价格')),
                ('volume', models.IntegerField(default='', verbose_name='成交量(股)')),
                ('amount', models.DecimalField(decimal_places='2', default='', max_digits='16', verbose_name='成交金额')),
                ('adjustflag', models.IntegerField(default='', verbose_name='复权类型')),
                ('turn', models.DecimalField(decimal_places='4', default='', max_digits='8', verbose_name='换手率')),
                ('tradestatus', models.IntegerField(default='', verbose_name='交易状态')),
                ('pct_chg', models.DecimalField(decimal_places='4', default='', max_digits='8', verbose_name='涨跌幅(百分比)')),
                ('pe_ttm', models.DecimalField(decimal_places='4', default='', max_digits='8', verbose_name='滚动市盈率')),
                ('pb_mrq', models.DecimalField(decimal_places='4', default='', max_digits='8', verbose_name='市净率')),
                ('ps_ttm', models.DecimalField(decimal_places='4', default='', max_digits='8', verbose_name='滚动市销率')),
                ('pcf_ncf_ttm', models.DecimalField(decimal_places='4', default='', max_digits='8', verbose_name='滚动市现率')),
                ('is_st', models.IntegerField(default='', max_length=8, verbose_name='是否ST(1是 0否)')),
            ],
        ),
    ]
