# Generated by Django 3.2.7 on 2021-10-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0003_kline_1d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline_1d',
            name='is_st',
            field=models.IntegerField(default='', verbose_name='是否ST(1是 0否)'),
        ),
    ]
