# Generated by Django 3.2.7 on 2021-10-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0008_auto_20211006_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline_1d',
            name='amount',
            field=models.DecimalField(decimal_places='2', max_digits='16', verbose_name='成交金额'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='pct_chg',
            field=models.DecimalField(decimal_places='4', max_digits='12', verbose_name='涨跌幅(百分比)'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='preclose',
            field=models.DecimalField(decimal_places='4', max_digits='10', verbose_name='前一天收盘价格'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='turn',
            field=models.DecimalField(decimal_places='4', max_digits='8', verbose_name='换手率'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='volume',
            field=models.IntegerField(verbose_name='成交量(股)'),
        ),
    ]
