# Generated by Django 3.2.7 on 2021-10-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0009_auto_20211006_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline_1d',
            name='adjustflag',
            field=models.IntegerField(default=0, verbose_name='复权类型'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='amount',
            field=models.DecimalField(decimal_places='2', default=0, max_digits='16', verbose_name='成交金额'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='close',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='10', verbose_name='收盘价格'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='high',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='10', verbose_name='最高价格'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='is_st',
            field=models.IntegerField(default=0, verbose_name='是否ST(1是 0否)'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='low',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='10', verbose_name='最低价格'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='open',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='10', verbose_name='开盘价格'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='pb_mrq',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='12', verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='pcf_ncf_ttm',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='12', verbose_name='滚动市现率'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='pct_chg',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='12', verbose_name='涨跌幅(百分比)'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='pe_ttm',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='12', verbose_name='滚动市盈率'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='preclose',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='10', verbose_name='前一天收盘价格'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='ps_ttm',
            field=models.DecimalField(decimal_places='4', default=0.0, max_digits='12', verbose_name='滚动市销率'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='tradestatus',
            field=models.IntegerField(default=0, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='kline_1d',
            name='volume',
            field=models.IntegerField(default=0, verbose_name='成交量(股)'),
        ),
    ]
