# Generated by Django 3.2.7 on 2021-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0010_auto_20211006_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline_1d',
            name='volume',
            field=models.BigIntegerField(default=0, verbose_name='成交量(股)'),
        ),
    ]
